### ISSUE TITLE
Travis CI failing on Windows

### ISSUE THREAD

**Issue by AndrewLeedham** [adobe/jwt-auth#30]
### Expected Behaviour
Travis CI installs node 8/10/12 on Windows.
### Actual Behaviour
Travis CI fails to install node 10/12 on Windows.
### Reproduce Scenario (including but not limited to)
Any PR.
#### Steps to Reproduce
Raise a PR.
#### Platform and Version
Travis CI > Windows > Node 10/12
#### Sample Code that illustrates the problem
N/A
#### Logs taken while reproducing problem
```
42.61s$ nvs add 10
Downloading bootstrap node from https://nodejs.org/dist/v10.12.0/node-v10.12.0-win-x64.7z
Failed to download node binary.
The command "nvs add 10" failed and exited with 1 during .
Your build has been stopped.
curl: (7) Failed to connect to nodejs.org port 443: Timed out
```
```
23.31s$ nvs add 12
Downloading bootstrap node from https://nodejs.org/dist/v10.12.0/node-v10.12.0-win-x64.7z
######################################################################## 100.0%
The command "nvs add 12" failed and exited with 1 during .
Your build has been stopped.
Failed to download file: https://nodejs.org/dist/v12.13.1/node-v12.13.1-win-x64.7z
connect ETIMEDOUT 104.20.22.46:443
```

**Comment by shazron** [comment]
Seems to be a problem with Windows on Travis CI (still in beta). If I restart a failed Windows job in the build matrix, usually it passes after.

**Comment by AndrewLeedham** [comment]
I think I fixed the issue in my PR with https://github.com/adobe/jwt-auth/pull/29/commits/30e9188497216ef370725e98372972d6e290fd2a works on the first run now. I was just raising this issue to give context to that fix.

**Comment by AndrewLeedham** [comment]
Seems to have been fixed on Travis CI's end: see https://github.com/adobe/jwt-auth/pull/32
