### ISSUE TITLE
Unable to install jwt-auth library in React Native 

### ISSUE THREAD

**Issue by shibinose** [adobe/jwt-auth#54]
npm install @adobe/jwt-auth command fails with React native framework. The error message says - "Unable to resolve the module 'crypto'".

Steps for reproducing this issue:

1. npm install @adobe/jwt-auth
    It throws an error "Unable to resolve module 'stream'"

2. npm install stream
 It throws an error "Unable to resolve module 'util'"

3. npm install util
 It throws an error "Unable to resolve module 'crypto'"

https://www.npmjs.com/package/crypto is deprecated and unable to install in react native. Please find attached the screenshots for more details.

![jwt auth error - 1](https://user-images.githubusercontent.com/7383082/141059961-bc572cd1-6276-4038-a2f6-f8e2ef64bd0b.png)
![jwt auth error - 2](https://user-images.githubusercontent.com/7383082/141059970-e9e74172-b6b3-4149-a8e8-9155a3d957dc.png)
![jwt auth error - 3](https://user-images.githubusercontent.com/7383082/141059973-850dddca-feec-4d4d-9a43-ff8b9053e821.png)
![crypto](https://user-images.githubusercontent.com/7383082/141060014-8cde63e6-1b76-48cb-8ade-d18288f8e4bc.png)

**Comment by shazron** [comment]
Seems fine to me:
```
$ node --version
v14.17.4
$ mkdir foo
$ cd foo
$ npm init -y
$ npm install @adobe/jwt-auth
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN foo@1.0.0 No description
npm WARN foo@1.0.0 No repository field.

+ @adobe/jwt-auth@1.0.1
added 26 packages from 22 contributors and audited 26 packages in 2.013s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by sumanth-kanukuntla** [comment]
node -v 10.15.3
react native 0.61.5
I have the same issue with the crypto library.

**Comment by shazron** [comment]
This module is not meant for React native because it uses node built in modules, so it is working as designed and won't be updated for react native support.
