### ISSUE TITLE
Trying to retrieve a token using an invalid metascope, should reject the promise.

### ISSUE THREAD

**Issue by dompuiu** [adobe/jwt-auth#6]
In Launch, we have a tool that helps our developers to upload extensions to our platform. In order to be able to upload an extension, we ask them to create integrations where they can select either the admin scope (ent_reactor_admin_sdk) or the extension developer scope (ent_reactor_extension_developer_sdk). Our tool tries to get an access token using one of these scopes. If it gets the `invalid_scope` error back, it tries to get a token using the other scope.

Using this code 
```
auth(config)
  .then(token => console.log(token))
  .catch(error => console.log(error));
```

we were receiving an object like `{ error_description: 'The metascopes in the JWT are not a subset of the metascopes in the binding.', error: 'invalid_scope' }` inside the promise `then`. I think it makes more sense to receive that inside the promise `catch`.

If you agree with this, then probably when the fetch command receives an HTTP code that is not inside the 200-299 range, the promise returned by the `jwt-auth` package should get rejected.

If you decide to do this change, one downside is that may break current implementations.

**Comment by macdonst** [comment]
@dompuiu can you try out the fix in the `issue6` branch? I agree with you on the behaviour and I'll bump the package to 0.1.0. I'm not too worried about a breaking change at this point as I can reach out to others using the package.

**Comment by dompuiu** [comment]
@macdonst I've tested the branch in my project. Looks good to me!

**Comment by macdonst** [comment]
@dompuiu thanks for the sanity check. Merged into master and released a 0.1.0 version of the package.

**Comment by kaizenjegan** [comment]
@dompuiu how did you resolve this? Im still getting this issue for using the photoshop api

**Comment by dompuiu** [comment]
@kaizenjegan This PR is just changing the way `jwt-auth` library is rejecting the auth promise.  If you are receiving the `invalid_scope` error then maybe your integration is not having the correct scopes configured.

**Comment by kaizenjegan** [comment]
hmm. ok will have to raise a ticket to adobe. Im just plugging in the scope value value that I see in the documentation https://www.adobe.io/authentication/auth-methods.html#!AdobeDocs/adobeio-auth/master/JWT/Scopes.md

Thank you for the prompt response!

**Comment by Trazzmonger** [comment]
Ugh, trying to use these Adobe APIs for the first time ... and I too am getting that same invalid_scope error claiming "The metascopes in the JWT are not a subset of the metascopes in the binding".  I too have opened a "case" with Adobe Support for this - but if anyone knows a fix for this, please provide details.
