### ISSUE TITLE
Support passphrase for the private key

### ISSUE THREAD

**Issue by shazron** [adobe/jwt-auth#7]
## Motivation

[aio-cli-plugin-jwt-auth](https://github.com/adobe/aio-cli-plugin-jwt-auth) uses the npm module `jsonwebtoken`, same as this module. We want to consolidate our usage by using this module only.

### Expected Behaviour
There is a way to specify the private key's passphrase.

### Actual Behaviour
There is no way to specify the private key's passphrase

#### Steps to Reproduce

Use a private key with a passphrase.

#### Implementation notes

According to `jsonwebtoken`'s [docs](https://github.com/auth0/node-jsonwebtoken#jwtsignpayload-secretorprivatekey-options-callback) (and our usage of it in aio-cli-plugin-jwt-auth), this module's `privateKey` parameter can be an object as well, with these keys: `{ key, passphrase }`.

In that case, this is just a matter of updating the documentation to show how to support passphrase in the `privateKey` parameter docs, or add a new parameter for passphrase. In our usage, passing in an empty string for passphrase  will work for keys with no passphrase.

I can send a PR if you have a preference for either approach.

**Comment by macdonst** [comment]
@shazron I merged the PR to support this new feature. Do you want me to release a new version or will you send a PR for #9 shortly?

**Comment by shazron** [comment]
@macdonst I think wait for my PR, will land it asap
