### ISSUE TITLE
Unify error format

### ISSUE THREAD

**Issue by dompuiu** [adobe/jwt-auth#8]
### Expected Behaviour
Let's say we have the following code:
```
auth(config)
  .then(token => console.log(token))
  .catch(error => console.log(`Error retrieving access token. ${error}`));
```

Sometimes `jwt-auth` throws a native error (eg. if we feed a public key as a private key). Other times it throws a native object (for JSON errors thrown by the API). It will be helpful to have one type of error.

### Actual Behaviour

In the case when an object is thrown as an error, the native object `toString` method will return 
`[object Object]`. Our error looks like `Error retrieving the access token. [object Object]` which is not optimal.

**Comment by shazron** [comment]
Can we wrap this into #9?

**Comment by dompuiu** [comment]
Yes. But it is @Aaronius fault that he doesn't read the comments from the PR request form. :p

**Comment by macdonst** [comment]
@dompuiu I'm going to mark this as a duplicate of #9 even though your's was the earlier issue. Should have a fix this week.
