### ISSUE TITLE
Make rejection values consistent

### ISSUE THREAD

**Issue by Aaronius** [adobe/jwt-auth#9]
### Expected Behaviour
A consistent pattern for rejection values.

### Actual Behaviour
When a failure occurs, sometimes the promise is rejected [with a string](https://github.com/adobe/jwt-auth/blob/e95f18f32e5ea0ca00b0a261ee28e9c8b4db77e8/index.js#L36), sometimes [with an error object](https://github.com/adobe/jwt-auth/blob/e95f18f32e5ea0ca00b0a261ee28e9c8b4db77e8/index.js#L63), and sometimes [with a deserialized API response object](https://github.com/adobe/jwt-auth/blob/e95f18f32e5ea0ca00b0a261ee28e9c8b4db77e8/index.js#L81). These differences make it difficult for consumers to handle errors in a sane way.

### Reproduce Scenario (including but not limited to)
See https://jira.corp.adobe.com/browse/DTM-13285 and accompanying [pull request](https://github.com/adobe/reactor-uploader/pull/23).

If we get an error from the API request, we need to handle the rejection in one way, while if we get an error from something else (like the private key being invalid), then we need to handle it a different way.

My personal preference would be that the library always rejects with an error object (instance of Error or something that extends Error) that has a `code` property on it that we can potentially then use for programmatic decisioning. See https://github.com/Aaronius/penpal#errors as an example. If I console log the error, I should see a useful error message.

#### Platform and Version

Node 10.15.3

#### Sample Code that illustrates the problem
https://github.com/adobe/reactor-uploader/pull/23/files#diff-6c6450b4843b250cc22850185489f5beL114

#### Logs taken while reproducing problem

**Comment by shazron** [comment]
(I have the same problem but I'm doing some gymnastics handling the rejected value by value type right now). I agree as well that it should always reject with an Error object. Not sure about defining a `code` property on the Error object, which might not be discoverable since it's not standard. 

So we might have to extend the Error object to support extended properties, but have a `toJSON` function on it, so we can define what the serialization looks like. (`toJSON` is what `JSON.stringify` will call on an object). A normal Error object does not have a `toJSON` defined however.

**Comment by Aaronius** [comment]
I can't really speak to the standardness of `code`, but this concept comes from errors in node: https://nodejs.org/api/errors.html#errors_error_code

**Comment by Aaronius** [comment]
I'm not really understanding how `toJSON` plays into this problem. If Error is used for all rejection values, it already has a `toString` on it that uses the `message` property to produce a message when the error is logged to the console.

**Comment by shazron** [comment]
Yeah that property is a Node.js only thing, not an EcmaScript standard thing. Which might be ok since I don't think this is targeting the browser.

**Comment by shazron** [comment]
I'm thinking about the 3rd case you mentioned, when it rejected with a JSON object. Setting a stringified object as the message might work as well if we want to simplify things.

**Comment by Aaronius** [comment]
I think for the 3rd case, jwt-auth should take `error_description` off the response object and use it for the error instance's message. If the response object doesn't have an `error_message`, then jwt-auth should probably serialize the response and create a message like "An unknown error occurred while swapping jwt. The response is as follows: <serialized response>".

**Comment by shazron** [comment]
cool, I like it. I'll see if I can create a PR (tomorrow), would be good to clean up my code with a better version...

**Comment by macdonst** [comment]
@shazron I look forward to your PR. We can get this issue and issue #7 into a `0.2.0` release in the next couple of days.

**Comment by shazron** [comment]
Leaving this here for reference. The error response is:
```
{
    "error": "<Error code>", // The error code (string)
    "error_description": "<Error Description>" // A human readable error description of what went wrong. Do not base logic on this value.
} 
```

**Comment by shazron** [comment]
See PR #11 for the implementation. The PR is still pending new tests for the new Errors.

**Comment by shazron** [comment]
Tests added. Please review the PR #11

**Comment by macdonst** [comment]
@shazron I merged your PR and I'll look at that travisci issue before releasing a 0.2.0 today.

**Comment by Aaronius** [comment]
Thanks @shazron!

**Comment by macdonst** [comment]
@Aaronius you can pick up the change in 0.2.0
